 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 21 * * *'

 jobs:
   unittests:
     name: ${{ matrix.os }}, ${{ matrix.environment-file }}
     runs-on: ${{ matrix.os }}
     #timeout-minutes: 25
     strategy:
       matrix:
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         environment-file: [ci/37.yaml, ci/38.yaml, ci/39.yaml]
     
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
       
       - name: setup micromamba
         uses: mamba-org/provision-with-micromamba@main
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
      
       - name: run tests - bash
         shell: bash -l {0}
         run: |
           python -c 'import libpysal; libpysal.examples.fetch_all()'
           pytest -v libpysal --cov=libpysal --cov-report=xml
         if: matrix.os != 'windows-latest'
       
       - name: run tests - powershell
         shell: powershell
         run:  |
           python -c 'import libpysal; libpysal.examples.fetch_all()'
           pytest -v libpysal --cov=libpysal --cov-report=xml
         if: matrix.os == 'windows-latest'
      
       - name: ${{ matrix.os }}, ${{ matrix.environment-file }}
         uses: codecov/codecov-action@v2 
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: libpysal-codecov
